### ISSUE TITLE
The plugin engine needs a "login" API

### ISSUE THREAD

**Issue by giastfader** [baasbox/baasbox#701]
This API shoud be something like:
Box.Users.login(username, password);
and should return a valid session token

The internal context should remain the same of the original plugin endpoint caller.

**Comment by Enuratique** [comment]
Agreed. I had to expose my own login script because I want to add lastLoginDate to the User object, and have it updated on login. I've pasted my code below (it should obviously be cleaned, inputs validated, etc) should anyone else need it (you call it the same way you would call the existing login method):

/* uncomment this snippet to write a script that replies on POST method */
http().post(function(req){
    var username = req.body.username;
    var password = req.body.password;
    var appcode = req.body.appcode;
    var uri = req.headers.Host[0];
    var data_to_send="&username="+username+"&password="+password+"&appcode="+appcode+"&"; //IMPORTANT: put ALWAYS '&' chars before and after the body when use the application/x-www-form-urlencoded content-type
    result=Box.WS.post(
    "http://"+uri+"/login",
        data_to_send,
        {
            params:{},
            headers:{"Content-Type":"application/x-www-form-urlencoded"}
        }
    );//post
    return {status: 200, content: result.body.data};    
});

**Comment by giastfader** [comment]
Now sessions can be managed (and created) within plugins #803
