### ISSUE TITLE
Document deletion should delete link to it

### ISSUE THREAD

**Issue by avently** [baasbox/baasbox#722]
When one of the two linked documents deleted Baasbox should delete link from one to another. Because link exists and connects to incorrect RIDs (null).

**Comment by giastfader** [comment]
Are you referring to the BaasBox Link feature, or to the OrientDB link field type?

**Comment by avently** [comment]
Baasbox link feature.

**Comment by giastfader** [comment]
Ok, got it.

**Comment by giastfader** [comment]
However this is strange because actually the code execute a deleteVertex() operation that should delete the links to
https://github.com/baasbox/baasbox/blob/master/app/com/baasbox/dao/NodeDao.java#L306

**Comment by avently** [comment]
Hm, I found some non-existing documents linked together via _node document. I'll recheck this. Maybe I'm wrong.

**Comment by avently** [comment]
@giastfader Oh, sorry for the delay. You were right! Everything is working fine.
I know, you are supercool in OrientDB and already wrote a book. Can you please tell me why did you make linking through _links field and _BB_NodeVertex? Why not just collection to collection as OrientDB docs recommended? Just trying to understand Baasbox logic:)

**Comment by giastfader** [comment]
@avently the reason is the ACL.
To create edges among nodes you must have permission to update BOTH nodes.
In many scenarios a user can read information stored in a node, but cannot update it.
Imagine a blog post, everyone can read it but if you want to leave a comment you should create a link between the post and your comment, but simply you can't.
So in BaasBox, documents are stored in classes that extend ORestricted, and have a _link field to a node that is managed internally without restrictions. In this way we can create "links" between documents.
It is just a workaround, at least until the OrientDB team does not implement other permissions like "can create edge" on nodes.
